<!DOCTYPE html>
<html>
<head>
  <title>Github User Demo</title>
  <script>
    class HttpError extends Error {
      constructor(response) {
        super(`${response.status} for ${response.url}`);
        this.name = 'HttpError';
        this.response = response;
      }
    }

    async function loadJson(url) {
      const response = await fetch(url);
      if (response.status === 200) {
        return response.json();
      } else {
        throw new HttpError(response);
      }
    }

    async function demoGithubUser() {
      const name = prompt('Github username을 입력하세요.');
      try {
        const user = await loadJson(`https://api.github.com/users/${name}`);
        console.log(`이름: ${user.name}`);
        return user;
      } catch (err) {
        if (err instanceof HttpError && err.response.status === 404) {
          console.log("일치하는 사용자가 없습니다. 다시 입력해 주세요.");
          return demoGithubUser();
        } else {
          throw err;
        }
      }
    }

    demoGithubUser().catch(err => {
      console.error(err);
    });
  </script>
</head>
<body>
</body>
</html>